/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.border.MatteBorder;

/**
 *
 * @author prasad
 */
public class CustomerDashboard extends javax.swing.JFrame {

    String user = "root", pass = "root";
    String cust_id;

    private CustomerDashboard() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form CustomerDashboard
     */
    private void Dashboard() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            DriverManager.registerDriver(new org.apache.derby.jdbc.ClientDriver());
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/database", user, pass);
//            String query = "insert into CUSTOMER(CUSTOMER_ID,CUSTOMER_NAME,CURRENT_ADDRESS,PASSWORD,DATE_OF_BIRTH,AGE,EMAIL,PHONE) VALUES(23,'PRANAV','HADSAR','12356','1999-10-13',19,'pra17u234@viit.ac.in',934527)";            PreparedStatement statement=con.prepareStatement(query);
            String query = "select * from apartment";
            PreparedStatement statement = con.prepareStatement(query);
            ResultSet rs = statement.executeQuery();

//            show apartments
            if (rs.next()) {
//                jLabelApartmentName.setText(rs.getString("APARTMENT_NAME"));
//                jLabelDeposit.setText(rs.getString("DEPOSIT"));
//                jLabelAddress.setText(rs.getString("ADDRESS"));
//                jLabelType.setText(rs.getString("TYPE"));
//                String get = "select PROPRIETOR_NAME from proprietor where proprietor_id=" + rs.getString("PROPRIETOR_ID");
//                PreparedStatement getname = con.prepareStatement(get);
//                ResultSet rName = getname.executeQuery();
//                rName.next();
//                jLabelProprietorName.setText(rName.getString(1));

            }
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }

    }

    public CustomerDashboard(String id) {
        initComponents();
        cust_id = id;
        Dashboard();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception ex) {
                }

                JFrame frame = new JFrame("Test");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.add(new TestPane());
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
//                jPanel4.add(new TestPane());
                 
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonEditProfile = new java.awt.Button();
        buttonChangePassword = new java.awt.Button();
        buttonLogout = new java.awt.Button();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apartment Info");
        setMaximumSize(new java.awt.Dimension(1164, 640));
        setMinimumSize(new java.awt.Dimension(1130, 640));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        buttonEditProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonEditProfile.setLabel("EDIT PROFILE");
        buttonEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditProfileActionPerformed(evt);
            }
        });

        buttonChangePassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonChangePassword.setLabel("CHANGE PASSWORD");
        buttonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangePasswordActionPerformed(evt);
            }
        });

        buttonLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonLogout.setLabel("LOGOUT");
        buttonLogout.setMinimumSize(new java.awt.Dimension(145, 30));
        buttonLogout.setPreferredSize(new java.awt.Dimension(141, 30));
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/building.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/A ARRAOW.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonEditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(22, 22, 22)
                .addComponent(buttonEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(buttonChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 270, 600);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(270, 0, 840, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditProfileActionPerformed
        // TODO add your handling code here:
        EditProfile ep = new EditProfile(cust_id, "CUSTOMER");
        ep.setVisible(true);
    }//GEN-LAST:event_buttonEditProfileActionPerformed

    private void buttonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangePasswordActionPerformed
        // TODO add your handling code here:
        ChangePassword cp = new ChangePassword(cust_id, "CUSTOMER");
        cp.setVisible(true);
    }//GEN-LAST:event_buttonChangePasswordActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonChangePassword;
    private java.awt.Button buttonEditProfile;
    private java.awt.Button buttonLogout;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    public class TestPane extends JPanel {
        
        private JPanel mainList;
        int row;
        String cnt;
        int count;

        public TestPane() {
            setLayout(new BorderLayout());
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                DriverManager.registerDriver(new org.apache.derby.jdbc.ClientDriver());
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/database", user, pass);
                String query = "SELECT * FROM APARTMENT";
                PreparedStatement statement = con.prepareStatement(query);
                ResultSet rs = statement.executeQuery();
                while (rs.next()) {
                    count++;
                }  
            } 
            catch (Exception e) {
                e.printStackTrace();
            }
            
            mainList = new JPanel(new GridBagLayout());
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridwidth = GridBagConstraints.REMAINDER;
            gbc.weightx = 1;
            gbc.weighty = 1;
            mainList.add(new JPanel(), gbc);

            add(new JScrollPane(mainList));

//            JButton add = new JButton("Add");
//            add.addActionListener(new ActionListener() {
//                @Override
//                public void actionPerformed(ActionEvent e) {
            for(int i=1;i<count+1;i++){
                
                JPanel panel = new JPanel();
                JButton edit = new JButton("Edit");
                JButton delete = new JButton("Delete");
                JButton more = new JButton("More..");
                panel.setLayout(null);
                JLabel jl = new JLabel();
                JLabel jl1 = new JLabel("Name:-");
                JLabel jadd = new JLabel("ADDRESS:- ");
                JLabel jladd = new JLabel();
                JLabel jdep = new JLabel("DEPOSIT:- ");
                JLabel jldep = new JLabel();
                JLabel jar = new JLabel("AREA:- ");
                JLabel jlar = new JLabel();
                JLabel jown = new JLabel("OWNER :-");
                JLabel jlown = new JLabel("Chetan Patil");
                
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    DriverManager.registerDriver(new org.apache.derby.jdbc.ClientDriver());
                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/database", user, pass);
                    String query = "SELECT * FROM APARTMENT WHERE APARTMENT_ID = "+i;
                    PreparedStatement statement = con.prepareStatement(query);
                    ResultSet rs = statement.executeQuery();
                    if (rs.next()) {
                        jl.setText(rs.getString("APARTMENT_NAME"));
                        jladd.setText(rs.getString("ADDRESS"));
                        jldep.setText(rs.getString("DEPOSIT"));
                        jlar.setText(rs.getString("TYPE"));
                    }  
                } 
                catch (Exception e) {
                    e.printStackTrace();
                }
               
                    jl1.setBounds(30, 20, 100, 20);
                    jl.setBounds(100, 20, 200, 20);
                    jadd.setBounds(30, 80, 100, 20);
                    jdep.setBounds(30, 140, 100, 20);
                    jladd.setBounds(120, 80, 600, 20);
                    jldep.setBounds(120, 140, 100, 20);
                    jown.setBounds(400, 20, 100, 20);
                    jar.setBounds(400, 140, 100, 20);
                    jlown.setBounds(500, 20, 200, 20);
                    jlar.setBounds(500, 140, 200, 20);
                    edit.setBounds(700, 140, 50, 20);
                    delete.setBounds(750, 140, 70, 20);
                    more.setBounds(820, 140, 70, 20);
                    jl1.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jl.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jadd.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jladd.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jdep.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jldep.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jar.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jlar.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jown.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jlown.setFont(new java.awt.Font("Tahoma", 1, 14));
                    panel.add(jl1);
                    panel.add(jl);
                    panel.add(jadd);
                    panel.add(jdep);
                    panel.add(jldep);
                    panel.add(jladd);
                    panel.add(jown);
                    panel.add(jlown);
                    panel.add(jlar);
                    panel.add(jar);
                    panel.add(more);
                    panel.setPreferredSize( new Dimension( 170, 200 ) );
                    panel.setBorder(new MatteBorder(0, 0, 1, 0, Color.RED));
                    GridBagConstraints gbcd = new GridBagConstraints();
                    gbcd.gridwidth = GridBagConstraints.REMAINDER;
                    gbcd.weightx = 1;
                    gbcd.fill = GridBagConstraints.HORIZONTAL;
                    mainList.add(panel, gbcd, 0);

                    validate();
                    repaint();
            }        
//                }
//            });

//            add(add, BorderLayout.SOUTH);

        }

        @Override
        public Dimension getPreferredSize() {
            return new Dimension(200, 200);
        }
    }
}
