/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.border.*;

/**
 *
 * @author Pranav
 */
public class PGDetails extends javax.swing.JFrame {

     String user = "root";
    String pass = "root";
    String p_id,apt_id="1";
    /**
     * Creates new form PGDetails
     */
    public PGDetails(String id) {
        initComponents();
        p_id=id;
        userList();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception ex) {
                }

                JFrame frame = new JFrame("Test");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.add(new TestPane());
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
//                jPanel4.add(new TestPane());
                 
            }
        });
    }

//    CONSTRUCTOR
    private PGDetails() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void userList() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            DriverManager.registerDriver(new org.apache.derby.jdbc.ClientDriver());
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/database", user, pass);
            String query = "Select * from apartment where proprietor_id="+p_id;
            PreparedStatement statement = con.prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
//                jLabelAddress.setText(rs.getString("ADDRESS"));
//                jLabelApartmentName.setText(rs.getString("APARTMENT_NAME"));
//                jLabelType.setText(rs.getString("APARTMENT_TYPE"));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonAddPG = new java.awt.Button();
        buttonChangePass = new java.awt.Button();
        jLabel21 = new javax.swing.JLabel();
        buttonEditProfile = new java.awt.Button();
        buttonLogOut = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 651));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        button1.setBackground(new java.awt.Color(255, 0, 0));
        button1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button1.setLabel("ADD");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/building.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));

        buttonAddPG.setBackground(new java.awt.Color(240, 240, 240));
        buttonAddPG.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonAddPG.setLabel("ADD");
        buttonAddPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPGActionPerformed(evt);
            }
        });

        buttonChangePass.setBackground(new java.awt.Color(240, 240, 240));
        buttonChangePass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonChangePass.setLabel("CHANGE PASSWORD");
        buttonChangePass.setName(""); // NOI18N
        buttonChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangePassActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/A ARRAOW.png"))); // NOI18N

        buttonEditProfile.setBackground(new java.awt.Color(240, 240, 240));
        buttonEditProfile.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonEditProfile.setLabel("EDIT PROFILE");
        buttonEditProfile.setName(""); // NOI18N
        buttonEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditProfileActionPerformed(evt);
            }
        });

        buttonLogOut.setBackground(new java.awt.Color(240, 240, 240));
        buttonLogOut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonLogOut.setLabel("LOG OUT");
        buttonLogOut.setName(""); // NOI18N
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonAddPG, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel21)
                .addGap(27, 27, 27)
                .addComponent(buttonAddPG, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(248, 148, 6));

        button12.setBackground(new java.awt.Color(255, 0, 0));
        button12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button12.setLabel("ADD");

        button13.setBackground(new java.awt.Color(255, 153, 0));
        button13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button13.setLabel("EDIT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button13, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(button13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 240, 620);

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(240, 0, 840, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangePassActionPerformed
        // TODO add your handling code here:
        ChangePassword c= new ChangePassword(p_id, "PROPRIETOR");
        c.setVisible(true);
    }//GEN-LAST:event_buttonChangePassActionPerformed

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogOutActionPerformed

    private void buttonAddPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPGActionPerformed
        // TODO add your handling code here:
        AddPG w = new AddPG(p_id);
        w.setVisible(true);
    }//GEN-LAST:event_buttonAddPGActionPerformed

    private void buttonEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditProfileActionPerformed
        // TODO add your handling code here:
        EditProfile e= new EditProfile(p_id, "PROPRIETOR");
        e.setVisible(true);
    }//GEN-LAST:event_buttonEditProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PGDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PGDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PGDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PGDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PGDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button buttonAddPG;
    private java.awt.Button buttonChangePass;
    private java.awt.Button buttonEditProfile;
    private java.awt.Button buttonLogOut;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
 
    public class TestPane extends JPanel {
        
        private JPanel mainList;
        int row;
        String cnt;
        int count;

        public TestPane() {
            setLayout(new BorderLayout());
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                DriverManager.registerDriver(new org.apache.derby.jdbc.ClientDriver());
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/database", user, pass);
                String query = "SELECT * FROM APARTMENT where proprietor_id="+p_id;
                PreparedStatement statement = con.prepareStatement(query);
                ResultSet rs = statement.executeQuery();
                while (rs.next()) {
                    count++;
                }  
            } 
            catch (Exception e) {
                e.printStackTrace();
            }
            
            mainList = new JPanel(new GridBagLayout());
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridwidth = GridBagConstraints.REMAINDER;
            gbc.weightx = 1;
            gbc.weighty = 1;
            mainList.add(new JPanel(), gbc);

            add(new JScrollPane(mainList));

//            JButton add = new JButton("Add");
//            add.addActionListener(new ActionListener() {
//                @Override
//                public void actionPerformed(ActionEvent e) {
            for(int i=1;i<count+1;i++){
                
                JPanel panel = new JPanel();
                JButton edit = new JButton("Edit");
                JButton delete = new JButton("Delete");
                JButton more = new JButton("More..");
                panel.setLayout(null);
                JLabel jl = new JLabel();
                JLabel jl1 = new JLabel("Name:-");
                JLabel jadd = new JLabel("ADDRESS:- ");
                JLabel jladd = new JLabel();
                JLabel jdep = new JLabel("DEPOSIT:- ");
                JLabel jldep = new JLabel();
                JLabel jar = new JLabel("AREA:- ");
                JLabel jlar = new JLabel();
                JLabel jown = new JLabel("OWNER :-");
                JLabel jlown = new JLabel("Chetan Patil");
                
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    DriverManager.registerDriver(new org.apache.derby.jdbc.ClientDriver());
                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/database", user, pass);
                    String query = "SELECT * FROM APARTMENT WHERE PROPRIETOR_ID = "+p_id+ "AND cnt_id="+i;
                    PreparedStatement statement = con.prepareStatement(query);
                    ResultSet rs = statement.executeQuery();
                    if (rs.next()) {
                        jl.setText(rs.getString("APARTMENT_NAME"));
                        jladd.setText(rs.getString("ADDRESS"));
                        jldep.setText(rs.getString("DEPOSIT"));
                        jlar.setText(rs.getString("TYPE"));
                    }  
                } 
                catch (Exception e) {
                    e.printStackTrace();
                }
               
                    jl1.setBounds(30, 20, 100, 20);
                    jl.setBounds(100, 20, 200, 20);
                    jadd.setBounds(30, 80, 100, 20);
                    jdep.setBounds(30, 140, 100, 20);
                    jladd.setBounds(120, 80, 600, 20);
                    jldep.setBounds(120, 140, 100, 20);
                    jown.setBounds(400, 20, 100, 20);
                    jar.setBounds(400, 140, 100, 20);
                    jlown.setBounds(500, 20, 200, 20);
                    jlar.setBounds(500, 140, 200, 20);
                    edit.setBounds(700, 140, 50, 20);
                    delete.setBounds(750, 140, 70, 20);
                    more.setBounds(820, 140, 70, 20);
                    jl1.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jl.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jadd.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jladd.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jdep.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jldep.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jar.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jlar.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jown.setFont(new java.awt.Font("Tahoma", 1, 14));
                    jlown.setFont(new java.awt.Font("Tahoma", 1, 14));
                    panel.add(jl1);
                    panel.add(jl);
                    panel.add(jadd);
                    panel.add(jdep);
                    panel.add(jldep);
                    panel.add(jladd);
                    panel.add(jown);
                    panel.add(jlown);
                    panel.add(jlar);
                    panel.add(jar);
                    panel.add(edit);
                    panel.add(delete);
                    panel.add(more);
                    panel.setPreferredSize( new Dimension( 170, 200 ) );
                    panel.setBorder(new MatteBorder(0, 0, 1, 0, Color.RED));
                    GridBagConstraints gbcd = new GridBagConstraints();
                    gbcd.gridwidth = GridBagConstraints.REMAINDER;
                    gbcd.weightx = 1;
                    gbcd.fill = GridBagConstraints.HORIZONTAL;
                    mainList.add(panel, gbcd, 0);

                    validate();
                    repaint();
            }        
//                }
//            });

//            add(add, BorderLayout.SOUTH);

        }

        @Override
        public Dimension getPreferredSize() {
            return new Dimension(200, 200);
        }
    }
}
